### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by rgieseke** [plaintextaccounting/plaintextaccounting.github.io#1]
Great initiative, thanks!

May I suggest renaming the repo to `plaintextaccounting.org`?

**Comment by simonmichael** [comment]
I'd like to, but as I understand it, the current name is required to make github serve it as the Github Pages site for the plaintextaccounting organization (which it needs to be so that it can have a custom domain).

**Comment by rgieseke** [comment]
Ah, okay ...

**Comment by simonmichael** [comment]
I've mentioned this in the README.
