### ISSUE TITLE
README mentions an etherpad but there is no link

### ISSUE THREAD

**Issue by mariosangiorgio** [plaintextaccounting/plaintextaccounting.github.io#10]
I wanted to report a Visual Studio Code extension I just created. The readme says:

> Several ways to contribute changes:
> A. drop link suggestions etc. on the etherpad linked in the site footer

but I cannot find such link. Is this still the recommended way to contribute?

**Comment by simonmichael** [comment]
Hi Mario,

I'm sorry, that instruction is obsolete and should be changed. A pull request to the github repo is the way.

**Comment by simonmichael** [comment]
Thank you!
