### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by dmp1ce** [plaintextaccounting/plaintextaccounting.github.io#38]
Can HTTPS be enabled for the website?

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by simonmichael** [comment]
Why ?

**Comment by simonmichael** [comment]
(Genuine question.) Also: I can see that https://plaintextaccounting.org does work right now, though it's not enforced. I don't know if that's new, I updated the [IP addresses](https://help.github.com/articles/troubleshooting-custom-domains/#https-errors) this morning.

**Comment by dmp1ce** [comment]
Cool. As long as the https is available then that is fine with me.

Reasons for why would might want https for only an informational site is to prevent a middle man from inserting code into your pages.

**Comment by colindean** [comment]
> to prevent a middle man from inserting code into your pages

This and

https://medium.com/@colindean/why-your-informational-website-should-use-https-369cfc853c29

**Comment by colindean** [comment]
It's probably not a bad thing to enforce it now that GitHub is handling the LetsEncrypt certificates.

**Comment by simonmichael** [comment]
Thanks all. That was informative @colindean. I'm sad about the passing of the http web, but I've made the site enforce https. Please let me know of any resulting breakage. Thanks to github and letsencrypt for making it super easy.
