### ISSUE TITLE
New link for importer

### ISSUE THREAD

**Issue by madhat2r** [plaintextaccounting/plaintextaccounting.github.io#4]
Here is a program I have released that downloads transaction from institutions via Plaid, and exports them into either beancount or ledger syntax. You can add this link to your page if you think it helpful to others.

https://github.com/madhat2r/plaid2text

**Comment by simonmichael** [comment]
Thanks! Linked and tweeted.

**Comment by madhat2r** [comment]
Great, thank you!

On May 15 at 10:24 AM, Simon Michael <notifications@github.com> said
thus:
> [ text/plain ]
> Thanks! Linked and tweeted.
>
