### ISSUE TITLE
Some links are wrong.

### ISSUE THREAD

**Issue by kunedo** [plaintextaccounting/plaintextaccounting.github.io#59]
Hi, I found some links are wrong, and I found some pages maybe the same page.

at https://plaintextaccounting.org/#comparisons:

article `Another Ledger user's perspective `, I found a page link is https://groups.google.com/d/msg/beancount/QV4qgpFbtJ8/9fSgMw-XGC8J

article `ledger vs hledger vs beancount or how to choose the right cli client`, I found a page too, 
https://ledger-cli.narkive.com/p6NyKbUY/ledger-vs-hledger-vs-beancount-or-how-to-choose-the-right-cli-client

and the link of article `Fabrice Niessen: Why Ledger?` is wrong.

**Comment by simonmichael** [comment]
Thanks for the report, now fixed.
