### ISSUE TITLE
[meta] Use github pages to automatically generate html files

### ISSUE THREAD

**Issue by hrj** [plaintextaccounting/plaintextaccounting.github.io#6]
Thanks for creating this website!

Github Pages can generate `html` files from `.md` files if configured to do so. The generation is done automatically for every push to the repository.

Using this will make it easier to contribute; there wouldn't be a need to run pandoc locally on the submitter's system.

I can help with setting it up, if the idea sounds good.

**Comment by simonmichael** [comment]
@hrj thanks! I think I had some reason for doing it this way - a desire/need for some rendering features of pandoc ? The ability to accurately render the site locally for efficient exploratory development ? But If you'd like to take a crack at it, please do.

**Comment by alexjj** [comment]
Better yet host on netlify.

Balance across their CDN, SSL with letsencrypt with your domain and it's free!

- Sign up for a netlify.com account (it's free). 
- Make a new app, link the github repo
- Enter `Make All` in the build command
- Watch it build and push.
- Every new commit will trigger an update

I just forked the repo and made a demo app on my account:
http://painter-storm-13262.netlify.com/

**Comment by simonmichael** [comment]
Thanks for the demo @alexjj!

Do you see a real need for the added complexity of CDN, SSL, netlify yet ? Less is more ?

Netlify would be an alternative to Github Pages, right ?

**Comment by simonmichael** [comment]
@hrj: I like the idea of easier contribution, and definitely not having to commit html as well as markdown. There are two features of the current setup that I find quite valuable: 

- pandoc's extremely robust and well specified rendering, which avoids time wasted on unpredictable/unfixable rendering glitches when doing anything adventurous with markup.

- the ability to render locally the same way as the public site, allowing changes and experiments to be tested.

Any thoughts on these ? 

If you want to set up a github pages demo, I'd be very interested to test it.

**Comment by alexjj** [comment]
Netlify is an alternative to github pages, but it allows you to continue to use  Pandoc but means contributors can just edit on Github without having to build the HTML themselves. 

It is no more complex than GitHub in my opinion. Github uses a CDN and SSL, for github.io URLs, just not for custom domains.

**Comment by hrj** [comment]
@simonmichael 

>     pandoc's extremely robust and well specified rendering, which avoids time wasted on unpredictable/unfixable rendering glitches when doing anything adventurous with markup.

I don't know much about that. I have created a few small websites with Github pages. I didn't come across any layout problems, but I was not very particular about layout with those websites. They were mostly textual in nature.

>     the ability to render locally the same way as the public site, allowing changes and experiments to be tested.

That is possible with GH pages. Their HTML converter can be installed locally and its output (html files) can be tested locally. Also, these files can be checked in to the repo similar to what you are doing with pandoc. 

For a demo, see [this website](https://bas-org.github.io/) which is powered by [this source](https://github.com/bas-org/bas-org.github.io).

**Comment by simonmichael** [comment]
Pandoc is simple and familiar for me, and I think an easy tool to install for contributors wanting a preview. (Easier than setting up local Github pages rendering.) Having to generate and commit html is annoying but easy (a simple make before commit, could be automated with a precommit hook) and not painful enough to make me want to change what's working.  Closing this for now.
