### ISSUE TITLE
Add piecash to "data import/conversion"

### ISSUE THREAD

**Issue by MisterY** [plaintextaccounting/plaintextaccounting.github.io#61]
[piecash](https://github.com/sdementen/piecash/) Python library has an option to export a GnuCash (v2 & 3) book to ledger format.

Also, has anyone managed to build the docs under Windows?

**Comment by simonmichael** [comment]
Thanks, I've added it.

Re windows - perhaps not. What problems are you having ?

**Comment by simonmichael** [comment]
I've updated the README, instructions should be workable on windows now. Please let me know/send updates if not.

**Comment by MisterY** [comment]
Thanks for updating the instructions! Now I know I can make small changes directly on the web. I guess it would also work if I run pandoc commands directly.

Depending on the hosting provider, it should also be possible to read .md files directly (i.e. or GitHub, GitLab, etc.).
