### ISSUE TITLE
Getting started with Ledger is ill-formatted

### ISSUE THREAD

**Issue by onyxperidot** [plaintextaccounting/plaintextaccounting.github.io#68]
The book at https://rolfschr.github.io/gswl-book/latest.html  is ill-formatted.

I have built another one from scratch, a PDF copy of which is attached.

[GettingStartedWithLedger.pdf](https://github.com/plaintextaccounting/plaintextaccounting.github.io/files/3311612/GettingStartedWithLedger.pdf)

The HTML version is here:
[GettingStartedWithLedger.txt](https://github.com/plaintextaccounting/plaintextaccounting.github.io/files/3311633/GettingStartedWithLedger.txt)

**Comment by simonmichael** [comment]
@onyxperidot great, thank you. Can you contact GSWL's author and get your changes merged ?

**Comment by onyxperidot** [comment]
>

**Comment by onyxperidot** [comment]
> @onyxperidot great, thank you. Can you contact GSWL's author and get your changes merged ?

He has already fixed it without my telling him.  The latest version of his book is here: 
https://github.com/rolfschr/GSWL-book/releases/download/1.2.0/GettingStartedWithLedger.html
