### ISSUE TITLE
Link to "signed numbers" is broken.

### ISSUE THREAD

**Issue by bradyt** [plaintextaccounting/plaintextaccounting.github.io#74]
At webpage https://plaintextaccounting.org, if I click on "signed numbers", it takes me to https://www.ledger-cli.org/#Stating-where-money-goes, which does not have such section. The source suggests it's correctly set to go to https://www.ledger-cli.org/3.0/doc/ledger3.html#Stating-where-money-goes, but something is amiss. I did not research further.

**Comment by colindean** [comment]
It looks like the www became necessary. I'll fix it!

**Comment by colindean** [comment]
Thanks for reporting it!
